part of '../../../../click_connect_ai_crm_ui.dart';

class _CallReviewTab extends StatelessWidget {
  const _CallReviewTab();

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [
      GlassCard(child: Row(children: const [CircleAvatar(backgroundColor: CcColors.purple, child: Text('P')), SizedBox(width: 10), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Priya Singh', style: TextStyle(fontWeight: FontWeight.w900)), Text('Telecaller', style: TextStyle(color: CcColors.textMuted))])), CcChip(label: 'Reviewing', color: CcColors.purple, filled: true)])),
      const SizedBox(height: 12),
      GlassCard(child: Column(children: const [
        KeyValueRow('Lead', 'Rahul Mehta', icon: Icons.person_outline_rounded),
        KeyValueRow('Mobile', '+91 98765 43210', icon: Icons.call_rounded),
        KeyValueRow('Call Time', '12 May 2025, 11:32 AM', icon: Icons.access_time_rounded),
        KeyValueRow('Duration', '04:26', icon: Icons.timer_outlined),
        KeyValueRow('Status', 'Connected', icon: Icons.check_circle_outline_rounded, valueColor: CcColors.green),
      ])),
      const SizedBox(height: 12),
      GlassCard(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: const [
        Text('Call Recording', style: TextStyle(fontWeight: FontWeight.w900)),
        SizedBox(height: 12),
        Row(children: [Icon(Icons.play_circle_fill_rounded, color: CcColors.blue500, size: 42), SizedBox(width: 10), Expanded(child: LinearProgressIndicator(value: .35, color: CcColors.blue500, backgroundColor: CcColors.line)), SizedBox(width: 8), Text('04:26')]),
      ])),
      const SizedBox(height: 12),
      GlassCard(gradient: LinearGradient(colors: [CcColors.purple.withValues(alpha: .22), CcColors.card]), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: const [
        Row(children: [Text('AI Summary', style: TextStyle(fontWeight: FontWeight.w900)), Spacer(), CcChip(label: 'Generated by AI', color: CcColors.purple, filled: true)]),
        SizedBox(height: 8),
        Text('Lead is interested in the product and asked about pricing and implementation time. Follow-up expected next week. High probability of conversion.', style: TextStyle(color: CcColors.textSoft, height: 1.4)),
        SizedBox(height: 12),
        KeyValueRow('Sentiment', 'Positive', valueColor: CcColors.green),
        KeyValueRow('Interest Level', 'High', valueColor: CcColors.green),
        KeyValueRow('Next Action', 'Share proposal and schedule demo', valueColor: CcColors.amber),
      ])),
      const SectionTitle('Manager Action'),
      Wrap(spacing: 8, runSpacing: 8, children: const [CcChip(label: 'Approve', color: CcColors.green, icon: Icons.check_rounded, filled: true), CcChip(label: 'Request Changes', color: CcColors.amber, icon: Icons.edit_rounded, filled: true), CcChip(label: 'Escalate', color: CcColors.red, icon: Icons.priority_high_rounded, filled: true)]),
      const SizedBox(height: 12),
      const TextField(maxLines: 3, decoration: InputDecoration(labelText: 'Add Remark', hintText: 'Write your feedback or remarks...')),
      const SizedBox(height: 14),
      Row(children: const [Expanded(child: PrimaryButton(label: 'Message', icon: Icons.chat_rounded, color: CcColors.green)), SizedBox(width: 10), Expanded(child: PrimaryButton(label: 'Save & Next', icon: Icons.arrow_forward_rounded))]),
    ]));
  }
}


